### ISSUE TITLE
Research: Python cloud functions?

### ISSUE THREAD

**Issue by jamarob** [arisslin/flattenthequeue#5]
- how can we run python in the cloud?
- what are the restrictions?

**Comment by albert-schilling** [comment]
# Research notes (27.04.2020)
## Keywords:
- Function-as-a-service
- event-driven (e.g. by a HTTP request), server-less computing 

## Requirements:
- invoked by HTTP request
- Python runtime environment

 ## Providers: 
- Google Cloud Functions
- AWS Lambda

## Ressources:
-	[Getting Started with Python for Google Cloud Functions](https://timberry.dev/posts/python-for-google-cloud-functions/)
## About Cloud Functions
-	The runtime for Cloud Functions uses the Flask library and provides us with a Request object that we can manipulate however we like.
-	Possible Triggers:
o	HTTP Requests (that can read out the Request and its JSON Object in the Request Body)
o	internal events from inside the Google ecosystem, e. g. upload to a Cloud Storage Bucket

**Comment by arisslin** [comment]
Good work!
